-- 第一题
CREATE TABLE `order1`(
	id INT  NOT NULL DEFAULT 0,
	goods_name VARCHAR(32) NOT NULL DEFAULT '',
	order_name VARCHAR(32) NOT NULL DEFAULT '',
	num INT NOT NULL DEFAULT 0
)
CREATE INDEX order1_index ON order1(id)
CREATE TABLE `order2`(
	id INT  NOT NULL DEFAULT 0,
	goods_name VARCHAR(32) NOT NULL DEFAULT '',
	order_name VARCHAR(32) NOT NULL DEFAULT '',
	num INT NOT NULL DEFAULT 0
) 
ALTER TABLE order2 ADD INDEX order2_index(id)


-- 第二题
CREATE TABLE menu1(
	id INT UNIQUE NOT NULL DEFAULT 0,
	`menu_name` VARCHAR(32) NOT NULL DEFAULT '',
	card_id CHAR(18) NOT NULL DEFAULT '',
	price DOUBLE NOT NULL DEFAULT 0
)
SHOW INDEXES FROM menu1
CREATE TABLE menu2(
	id INT  NOT NULL DEFAULT 0,
	`menu_name` VARCHAR(32) NOT NULL DEFAULT '',
	card_id CHAR(18) NOT NULL DEFAULT '',
	price DOUBLE NOT NULL DEFAULT 0
)
CREATE UNIQUE INDEX menu2_index ON menu1(id)
SHOW INDEXES FROM menu2

CREATE TABLE sportman1 (
	id  INT UNIQUE NOT NULL DEFAULT 0,
	`name` VARCHAR(32) NOT NULL DEFAULT '',
	skill VARCHAR(32) NOT NULL DEFAULT ''
)
CREATE INDEX man1_index ON sportman1(`name`)
SHOW INDEXES FROM sportman1
CREATE TABLE sportman2 (
	id  INT UNIQUE NOT NULL DEFAULT 0,
	`name` VARCHAR(32) NOT NULL DEFAULT '',
	skill VARCHAR(32) NOT NULL DEFAULT ''
)
ALTER TABLE sportman2 ADD INDEX man2_index(`name`)
SHOW INDEXES FROM sportman2